keys:
  - &personal-air age17jsegwkxmgth2dy94wy8xqkhftuw5zzu7hy0dzqv5qerh5wdl5gqgwsw5v
  - &asahi-mini age18lcnglsuw3la0dphqvpt4r3rktq5j7uf5d4m6hrdsjz2glnyrvusmm4kjn
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *asahi-mini
      - *personal-air
