#! /bin/sh

bspc monitor DVI-0 -d I II III IV V
bspc monitor DVI-1 -d VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          5
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding 15
bspc config focus_follows_pointer true

${HOME}/.config/bspwm/panel
