#!/bin/sh

source ~/.config/bspwm/profile
source ~/.config/bspwm/panel_colors


if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
echo 'T' $ORANGE $(whoami)@$(hostname) > "$PANEL_FIFO" &

# Loop to check time, battery and volume statuses
while true; do
    AP=$(essid -w wlp3s0)
    VOL=$(amixer get Master | egrep -o "[0-9]+%")
    DATE=$(date +'S%B %d %a %H:%M')
    echo 'I'$LIGHTGREY$AP$FG' ⮞ '$LIGHTGREY$VOL% $FG'⮏'$LIGHTGREY $FG> "$PANEL_FIFO" &
    echo "$DATE "  > "$PANEL_FIFO" &
sleep 0.5s
done &

cat "$PANEL_FIFO" | ~/.config/bspwm/panel_bar | bar -g ${BARWIDTH}x${BARHEIGHT}+${EDGEWIDTH} -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
